// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVMZH69B0Pqb4RZZNs8XL0FwBYkPVoKzo',
    appId: '1:183973726892:web:2b5f9913578a21fb416d09',
    messagingSenderId: '183973726892',
    projectId: 'social-market-54482',
    authDomain: 'social-market-54482.firebaseapp.com',
    storageBucket: 'social-market-54482.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClGK9_ZNGYfZy2uu54s03mZe2Upqu6mhA',
    appId: '1:183973726892:android:22454033781defda416d09',
    messagingSenderId: '183973726892',
    projectId: 'social-market-54482',
    storageBucket: 'social-market-54482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8UlJOgYGz4EykQVd-x38j5YrbHav1p2Q',
    appId: '1:183973726892:ios:90a6986a422157e5416d09',
    messagingSenderId: '183973726892',
    projectId: 'social-market-54482',
    storageBucket: 'social-market-54482.firebasestorage.app',
    iosBundleId: 'com.example.socialMarketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8UlJOgYGz4EykQVd-x38j5YrbHav1p2Q',
    appId: '1:183973726892:ios:90a6986a422157e5416d09',
    messagingSenderId: '183973726892',
    projectId: 'social-market-54482',
    storageBucket: 'social-market-54482.firebasestorage.app',
    iosBundleId: 'com.example.socialMarketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVMZH69B0Pqb4RZZNs8XL0FwBYkPVoKzo',
    appId: '1:183973726892:web:59f33f44b285d6c1416d09',
    messagingSenderId: '183973726892',
    projectId: 'social-market-54482',
    authDomain: 'social-market-54482.firebaseapp.com',
    storageBucket: 'social-market-54482.firebasestorage.app',
  );
}
